version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test5Project
  gitServerName: https://github.com/
  gitUrl: https://github.com/y509522/Test5Project
  gitUsername: y509522
  gitBranch: deploy-1
services:
- serviceName: project.test5.integrations:Test
  packages:
  - name: Test5Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.0.0.0.903
- serviceName: project.test5.integrations:addInt
  packages:
  - name: Test5Project
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.903
